apiVersion: batch/v1
kind: Job
metadata:
  name: playlist-rules-generator
  namespace: lucasmaia
spec:
  template:
    metadata:
      labels:
        app: playlist-rules-generator
    spec:
      containers:
        - name: playlist-rules-generator
          image: lucasmaia96/playlist-rules-generator:05
          volumeMounts:
            - name: shared-volume
              mountPath: /mnt/shared
      restartPolicy: Never
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: project2-pv2-lucasmaia-claim
