apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv2-lucasmaia-claim
  namespace: lucasmaia
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: lucasmaia
  storageClassName: default-storage-class-lucasmaia
